version: 2.1.0.{build}
image: Visual Studio 2017
environment:
  $msbuildPath: $(cmd /c where msbuild)

configuration: Release

after_build:
  - ps: >-
      . .\build.ps1 Pack-Nuget
artifacts:
  - path: boleto2net\lib
    name: src

deploy:
- provider: NuGet
  server: https://www.myget.org/F/boleto2netbuild/
  api_key:
    secure: rH9VFKFXJsR5D07BF9PayFm7mRo7acVANtfgYkGa3S9ybX0RCWBiSM153yhLaorG
  skip_symbols: true
  on:
    branch: master
    
notifications:
- provider: Email
  to:
  - cds@cds-software.com.br
  subject: Boleto2Net Build
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
